econf/urls.py
from django.conf import settings
from django.conf.urls import patterns, include, url

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
from django.contrib.auth.decorators import login_required, user_passes_test
from django.contrib.formtools.preview import FormPreview
from confapp.forms import AccountFormPreview, AccountForm
from confapp.views import PaperDelete, ReviewUpdate

admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'econf.views.home', name='home'),
    # url(r'^econf/', include('econf.foo.urls')),

    (r'^$', 'confapp.views.main'),

    #(r'^register$', 'confapp.views.register'),
    (r'^register$', user_passes_test(lambda u: not u.is_authenticated(), '/logout')(AccountFormPreview(AccountForm))),
    (r'^accounts/profile/$', 'confapp.views.update_account'),
    (r'^contact$', 'confapp.views.contact'),

    (r'^review/(\d+$)', 'confapp.views.review_paper'),

    (r'^papers/delete/(?P<pk>\d+)$', PaperDelete.as_view()),
    (r'^papers/$', 'confapp.views.paper'),
    (r'^papers/(?P<pk>\d+)$', 'confapp.views.paper'),
#    (r'^papers/(?P<pk>\d+)$', PaperUpdate.as_view()),
#    (r'^papers/$', PaperCreate.as_view()),

    (r'^attachments/(?P<id>\d+)$', 'confapp.views.get_attachment'),

    (r'^accounts/changepass/$', 'django.contrib.auth.views.password_change'),
    (r'^accounts/changepassdone$', 'django.contrib.auth.views.password_change_done'),
    (r'^login$', 'django.contrib.auth.views.login'),
    (r'^logout$', 'django.contrib.auth.views.logout', {'next_page':'/'}),

#    (r'^login$', 'confapp.views.login'),
#    (r'^logout$', 'confapp.views.logout'),
    #(r'^changepass$', 'confapp.views.changepass'),


    # Uncomment the admin/doc line below to enable admin documentation:
    url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    url(r'^admin/', include(admin.site.urls)),
)

if settings.DEBUG:
    urlpatterns += patterns('',
        url(r'^media/(?P<path>.*)$', 'django.views.static.serve', {
            'document_root': settings.MEDIA_ROOT,
            }),
    )

confapp/models.py
# -*- coding: utf-8 -*-

from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_save

class Conference(models.Model):
    name = models.CharField(max_length=255)
    date = models.DateField()
    email = models.EmailField()

    def __unicode__(self):
        return self.name


class Review(models.Model):
    paper = models.OneToOneField('Paper')

    NO = 0
    PARTIALLY = 1
    YES = 2

    UNACCEPTABLE = 0
    ACCEPTABLE = 1
    GOOD = 2

    REJECT = 0
    REVIEW_REVISED = 1
    PUBLISH_REVISED = 2
    PUBLISH = 3

    CHOICES1 = (
        (NO, 'Nie'),
        (PARTIALLY, u'Częściowo'),
        (YES, 'Tak'),
    )
    CHOICES2 = (
        (UNACCEPTABLE, u'Niezadowalająca'),
        (ACCEPTABLE, u'Zadowalająca'),
        (GOOD, 'Bardzo dobra'),
    )
    CHOICES3 = tuple([(i+1, i+1) for i in range(5)])
    CHOICES4 = (
        (REJECT, u'Odrzucić'),
        (REVIEW_REVISED, u'Poprawioną wersję poddać ponownej recenzji'),
        (PUBLISH_REVISED, u'Opublikować po korekcie'),
        (PUBLISH, u'Opublikować bez poprawek'),
    )

    original = models.IntegerField(choices = CHOICES1, default = 0)
    significant = models.IntegerField(choices = CHOICES1, default = 0)
    clear = models.IntegerField(choices = CHOICES1, default = 0)
    correct = models.IntegerField(choices = CHOICES1, default = 0)
    citing = models.IntegerField(choices = CHOICES1, default = 0)
    figures = models.IntegerField(choices = CHOICES1, default = 0)

    adequacy = models.IntegerField(choices = CHOICES2, default = 0)
    novelty = models.IntegerField(choices = CHOICES2, default = 0)

    rating = models.IntegerField(choices = CHOICES3, default = 0)
    summary = models.IntegerField(choices = CHOICES4, default = 0)

    remarks = models.TextField(verbose_name='Remarks', blank=True)
    comments = models.TextField(verbose_name='Comments', blank=True)


class Account(models.Model):
    user = models.OneToOneField(User)

    organization = models.CharField(verbose_name='Organizacja', max_length=255)
    institute = models.CharField(verbose_name='Jednostka', max_length=255)
    city = models.CharField(verbose_name='Miasto', max_length=50)
    postcode = models.CharField(verbose_name='Kod pocztowy', max_length=6)
    address = models.CharField(verbose_name='Adres', max_length=255)

    nip = models.CharField(verbose_name='Numer NIP', max_length=30)

    accounttype = models.ForeignKey('AccountType', default=0, verbose_name='Uczestnictwo')

    phone = models.CharField(verbose_name='Telefon', max_length=255)

    address2 = models.TextField(verbose_name='Adres do korespondencji', blank=True)

    def __unicode__(self):
        return '%s %s' % (self.user.first_name, self.user.last_name)


class AccountType(models.Model):
    name = models.CharField(max_length=30)
    payment = models.DecimalField(max_digits=6, decimal_places=2)

    def __unicode__(self):
        return '%s (%.2f PLN)' % (self.name, self.payment)


class Paper(models.Model):
    account = models.ForeignKey(Account, editable = False)
    title = models.CharField(max_length = 256, verbose_name=u'Tytuł')
    authors = models.CharField(max_length = 256, verbose_name='Autorzy')
    abstract = models.TextField(verbose_name="Abstrakt", blank = True)
    session = models.ForeignKey('SessionType', default = 0, verbose_name = 'Sesja')
    reviewer = models.ForeignKey(Account, editable = True, related_name= 'review_papers', null = True)

    def __unicode__(self):
        return '%s (Sesja %s)' % (self.title, str(self.session))

    def get_absolute_url(self):
        return '/papers/%d' % self.id


class SessionType(models.Model):
    name = models.CharField(max_length=32)

    def __unicode__(self):
        return self.name


class Attachment(models.Model):
    class Meta:
        ordering = ['-created']

    ARTICLE = 0
    PRESENTATION = 1
    TYPE_CHOICES = (
        (ARTICLE, 'Artykuł'),
        (PRESENTATION, 'Prezentacja'),
    )

    paper = models.ForeignKey(Paper, editable = False)
    created = models.DateTimeField(auto_now_add = True)
    type = models.IntegerField(choices = TYPE_CHOICES, default = ARTICLE)
    file = models.FileField(upload_to='attachments')

def create_user_account(sender, instance, created, **kwargs):
	if created:
		Account.objects.create(user=instance)

post_save.connect(create_user_account, sender=User)

confapp/forms.py
# -*- coding: utf-8 -*-
import django
from django.contrib import messages

from django.contrib.auth.models import User
from django.contrib.formtools.preview import FormPreview
from django import forms
from django.core import serializers
from django.core.exceptions import ValidationError
from django.core.mail import send_mail
from django.forms import widgets, Select
from django.forms.models import ModelForm
from django.http import HttpResponseRedirect
from django.template import Context
from django.template.response import TemplateResponse
import smtplib
from confapp.models import Account, Paper, Attachment, AccountType, Review
from django.conf import settings

class AccountForm(ModelForm):
    class Meta:
        model = Account
        #fields = ('first_name', 'last_name')
        exclude = ('user', )
        widgets = {
            'accounttype': widgets.RadioSelect()
        }

    first_name = forms.CharField(label=u'Imię', max_length=30)
    last_name = forms.CharField(label='Nazwisko', max_length=30)
    email = forms.EmailField()
    password = forms.CharField(widget = widgets.PasswordInput(), label='Hasło')
    password2 = forms.CharField(widget = widgets.PasswordInput(), label='Powtórz hasło')

    accounttype = forms.ModelChoiceField(queryset = AccountType.objects.all().order_by('id'),
        label='Uczestnictwo', initial=1)

    required_css_class = "required"
    error_css_class = "error"

    def __init__(self, *args, **kw):
        super(AccountForm, self).__init__(*args, **kw)
        self.requser = None
        self.fields.keyOrder = [
            'first_name',
            'last_name',
            'email',
            'password',
            'password2',
            'organization',
            'institute',
            'address',
            'postcode',
            'city',
            'nip',
            'accounttype',
            'phone',
            'address2'
        ]

    def clean_password(self):
        if len(self.cleaned_data['password']) < 6:
            raise forms.ValidationError('Podaj hasło co najmniej 6-znakowe')
        return self.cleaned_data['password']

    def clean(self):
        cleaned_data = super(AccountForm, self).clean()
#        print cleaned_data
        if 'password' in self.cleaned_data and 'password2' in self.cleaned_data:
            if self.cleaned_data['password'] != self.cleaned_data['password2']:
                raise forms.ValidationError('Podałeś różne hasła')
        return cleaned_data

    def clean_email(self):
        data = self.cleaned_data['email']
        try:
            User.objects.get(email=data)
            if not self.requser or not data == self.requser.email:
                raise forms.ValidationError('W systemie jest już zarejestrowany taki adres e-mail')
        except User.DoesNotExist:
            pass
        return data


    #	def clean(self):
    #		cleaned_data = super(AccountForm, self).clean()
    #		try:
    #			User.objects.get(email = cleaned_data['email'])
    #			self._errors['email'] = self.error_class(['Jest taki user'])
    #			del cleaned_data['email']
    #		finally:
    #			return cleaned_data


    def save(self, commit = True):
        account = super(AccountForm, self).save(commit=False)
        if self.requser: # TODO zrobic to lepiej, czytelniej
            # account update
            account.user.first_name=self.cleaned_data['first_name']
            account.user.last_name=self.cleaned_data['last_name']
            account.user.username=self.cleaned_data['email']
            account.user.email=self.cleaned_data['email']
            account.user.save()
            account.save()
            return account
        user = User(
            first_name=self.cleaned_data['first_name'],
            last_name=self.cleaned_data['last_name'],
            username=self.cleaned_data['email'],
            email=self.cleaned_data['email'])
#        print "Ustawiam haslo: %s" % self.cleaned_data['password']
        user.set_password(self.cleaned_data['password'])
        if commit:
            user.save()
            # Caution! Account objects is created automatically, due to User signal!
            account.id = user.account.id
            account.user = user
            account.save()
#            print account
        else:
            account.user = user
            user.account = account
        user.cleartext = self.cleaned_data['password'] # required to send the mail with confirmation
        return account


class AccountFormPreview(FormPreview):
#    preview_template = 'formtools/preview.html'
    form_template = 'registration/form.html'

    def process_preview(self, request, form, context):
#        print dir(context['form'].fields['accounttype'].widget)
        context['accounttype'] = form.instance.accounttype.name

    def done(self, req, cleaned_data):
        form = AccountForm(req.POST)

        account = form.save(commit = True)
        try:
            t = django.template.loader.get_template('registration/mail.txt')
            user = account.user
            user.account = account
            c = Context({'user': user})
            body = t.render(c)
            #send_mail('Forum Innowacji Młodych Badaczy -- potwierdzenie rejestracji',
                #body, 'Komitet Organizacyjny <%s>' % settings.EMAIL_HOST_USER, [cleaned_data['email']])
            try:
                yamldata = serializers.serialize('yaml', [account.user, account])
                send_mail(u'[FIMB] Rejestracja uczestnika: %s <%s>' % (unicode(account), account.user.email),
                    yamldata, 'econf <%s>' % settings.EMAIL_HOST_USER, [settings.EMAIL_HOST_USER])
            except Exception, e:
                print e
                raise
            messages.success(req, 'Dziękujemy za rejestrację. Dostaniesz maila z potwierdzeniem.')
            return HttpResponseRedirect('/')
        except smtplib.SMTPException, e:
            print e
            return TemplateResponse(req, "thanks.html", {'mailerror':True})


class ContactForm(forms.Form):
    message = forms.CharField(widget = widgets.Textarea(), label='Treść wiadomości')
    sendcopy = forms.BooleanField(initial = True, required = False)

class ReviewForm(ModelForm):

    original = forms.ChoiceField(widget=forms.Select, choices=(('','-- Wybierz --'),)+Review.CHOICES1)
#    original = models.IntegerField(choices = CHOICES1, default = 0)
    significant = forms.ChoiceField(widget=forms.Select, choices=(('','-- Wybierz --'),)+Review.CHOICES1)
    clear = forms.ChoiceField(widget=forms.Select, choices=(('','-- Wybierz --'),)+Review.CHOICES1)
    correct = forms.ChoiceField(widget=forms.Select, choices=(('','-- Wybierz --'),)+Review.CHOICES1)
    citing = forms.ChoiceField(widget=forms.Select, choices=(('','-- Wybierz --'),)+Review.CHOICES1)
    figures = forms.ChoiceField(widget=forms.Select, choices=(('','-- Wybierz --'),)+Review.CHOICES1)

    adequacy = forms.ChoiceField(widget=forms.Select, choices=(('','-- Wybierz --'),)+Review.CHOICES2)
    novelty = forms.ChoiceField(widget=forms.Select, choices=(('','-- Wybierz --'),)+Review.CHOICES2)

    rating = forms.ChoiceField(widget=forms.Select, choices=(('','-- Wybierz --'),)+Review.CHOICES3)
    summary = forms.ChoiceField(widget=forms.Select, choices=(('','-- Wybierz --'),)+Review.CHOICES4)


    class Meta:
        model = Review
        exclude = ('paper',)
        widgets = {
            #'original': Select(choices = ((-1, 'Wybierz'),))
        }


class PaperForm(ModelForm):
    class Meta:
        model = Paper
#        exclude = ('user', )
#        fields = ('first_name', 'last_name')

    required_css_class = "required"
    error_css_class = "error"

    attachment = forms.FileField(label='Plik', required = False)
    type = forms.ChoiceField(choices = Attachment.TYPE_CHOICES, label='Typ')

    def clean_attachment(self):
        attachment = self.cleaned_data['attachment']
        # print attachment._size
        if attachment is not None and attachment._size > settings.MAX_UPLOAD_SIZE:
            raise ValidationError('Dopuszczalny rozmiar pliku: %d MB' % (settings.MAX_UPLOAD_SIZE / 1024/1024))
        return attachment

templates/base.html
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="pl" lang="pl">
<head>
    <title>System zarządzania konferencjami</title>
    <meta http-equiv="content-type" content="text/html;charset=utf-8" />
    <link rel="stylesheet" type="text/css" href="/static/css/main.css" />
    <script src="js/jquery.js" type="text/javascript"></script>
	<script>
		setTimeout(function(){
			document.getElementById('message').style.display = 'none';
		}, 10000);
	</script>
</head>
<body>
<div class="page">
   <!-- <div class="header">
        <h1 onclick="location.href='/';"><a href="/">System zarządzania konferencjami</a></h1>
    </div>-->
	   <div class="message" >
	       {# MESSAGES  ("Profil zaktualizowano" etc.) #}
		  
		{% if messages %}
        
            <ul id="message">
                {% for message in messages %}
                    <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
                {% endfor %}
            </ul>
        
		{% endif %}
		</div>
    <div class="body">
      
	 
		 <div class="user_info"> 
			{%  if user.is_anonymous %}
				<!-- Posiadasz już konto? <a href="/login">Zaloguj się.</a><br/> -->
			{%  else %}
				Witaj, {{ user.account }}
				{% if user.is_staff %}
					<b>(admin)</b>
                {% elif user.account.accounttype.id == 4  %}
                    <b>(recenzent)</b>
				{% endif %}

				<a href="/logout">wyloguj</a>
			{%  endif %}
		</div>
      




        {% block content %}

        {# MAIN CONTENT HERE #}

        {% endblock %}

    </div>
    <div class="footer">
   
    </div>
</div>
</body>
</html>

templates/contact.html
{% extends "base.html" %}

{% block content %}
<div class="my_account">
<h1>Forum Innowacji Młodych Badaczy</h1>
<h2>Wiadomość do organizatorów</h2>
<div class="contact_form">
    <form action="" method="post">{% csrf_token %}

       <label> {{ form.message.label }}:</label>
	   
        {{ form.message }}
        {{ form.message.errors }}

       
		<p style="padding-top:10px;">
			<label for="id_sendcopy">Wyślij do mnie kopię: </label>
			{{ form.sendcopy }} 
		</p>
       
        <input type="submit" value="Wyślij" class="button" />
    </form>
</div>
</div>
{% endblock %}

templates/main.html
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <!-- <link rel="stylesheet" type="text/css" href="/static/css/main.css" /> -->
</head>


<body>

<h1>System zarządzania konferencjami</h1>

{% block contents %}

Zarejestrowani użytkownicy:
<ol>
{% for u in users %}
	<li>{{ u }}</li>
{% endfor %}
</ol>
<a href="/register">Zarejestruj się</a>

{% endblock %}

<br> <br> <br> <br> <br>
<a href="/admin/">logowanie</a>

{{ request }}

{% include "footer.html" %}

</body>
</html>

templates/panel.html
{% extends "base.html" %}

{% block content %}
<div class="my_account">
<h1>Forum Innowacji Młodych Badaczy</h1>

    <div>{{ message }}</div>
<div class="menu_left">

    <ul class="menu_left_list" >
		<li style="background-color:#777777; color:white; font-weight:bold ">MOJE KONTO:</li>
        <li><a href="/accounts/changepass/">Zmiana hasła</a></li>
        <li><a href="/accounts/profile/">Aktualizacja danych</a></li>
        <li><a href="/contact">Wiadomość do organizatorów</a></li>
    </ul>
</div>

{% if papers %}
<div class="my_papers">
    <ul class="menu_left_list">
	<li style="background-color:#777777; color:white; font-weight:bold; ">MOJE REFERATY: <a class="add" href="/papers/">Dodaj nowy</a> </li>
	
    {% for paper in papers %}
        <li><a href="/papers/{{ paper.id }}">{{ paper }}</a> <a class="delete" href="/papers/delete/{{ paper.id }}">usuń</a></li>
    {% endfor %}
    </ul>
</div>
{% endif %}

{% if user.account.accounttype.id == 4 %}
<div class="my_papers">
    <ul class="menu_left_list">
        <li style="background-color:#777777; color:white; font-weight:bold; ">ARTYKUŁY DO ZRECENZOWANIA:</li>

        {% for paper in toreview %}
            <li><a href="/review/{{ paper.id }}">{{ paper }}</a> </li>
        {% endfor %}
    </ul>
</div>
{% endif %}


<div class="if_admin">
{% if user.is_staff %}


    <ul class="registered_users" > &nbsp;
	<li style="background-color:#777777; color:white; font-weight:bold; ">Zarejestrowani użytkownicy:</li>
        {% for a in accounts %}
            <li>{{ a }} ({{ a.paper_set.all|length }} artykułów)</li>
        {% endfor %}
    </ul>

{% endif %}

{% endblock %}
</div>
</div>

templates/thanks.html
{% extends "base.html" %}

{% block content %}

Dziękujemy za rejestrację.

{% if not mailerror %}
    Dostaniesz maila z potwierdzeniem.
{% else %}
    Błąd podczas wysyłania maila z potwierdzeniem. Skontaktuj się z nami pod adresem info@fimb.p.lodz.pl.
{% endif %}

{% endblock %}